# Generated by Django 4.1.5 on 2024-08-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0022_editing_delete_writhing_editing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='title',
        ),
    ]
