# Generated by Django 4.1.5 on 2024-08-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0023_remove_transcription_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='business_plan',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='editing',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='graphicsdesignsubmission',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='programmingprojectsubmission',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='research',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='videoeditingsubmission',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='website_project',
            name='deadline',
        ),
    ]
