# Generated by Django 4.1.5 on 2024-08-12 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0025_assignment_ordered_at_business_plan_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='abstract',
            field=models.FileField(upload_to='assignment/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='business_plan',
            name='abstract',
            field=models.FileField(upload_to='business_plan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='graphicsdesignsubmission',
            name='design_file',
            field=models.FileField(upload_to='designs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['psd', 'ai', 'tiff', 'indd', 'png', 'jpeg', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='programmingprojectsubmission',
            name='project_file',
            field=models.FileField(upload_to='programming/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rar', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.FileField(upload_to='abstract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.FileField(upload_to='Thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'docx'])]),
        ),
    ]
