# Generated by Django 4.1.5 on 2024-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0028_alter_assignment_gender_alter_business_plan_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
