# Generated by Django 4.1.5 on 2024-08-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDER', '0029_alter_assignment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
